model:
  type: ecdp
  input_channels: 3
  sr_factor: 8

  rrdb_num_blocks: 8
  rrdb_block_selection: [1, 3, 5, 7]
  rrdb_network_features: 64
  rrdb_intermediate_features: 32
  rrdb_channels: 256  # rrdb_network_features * len(rrdb_block_selection)


  prior: gaussian

train:
  use_cuda: true
  tensorboard: true
  random_seed: null
  distributed: false

  finetune_pretrained_model: results/your-experiment-name/checkpoints/checkpoint.pt
  finetune_percep: true
  finetune_pixel: false
  finetune_gan: false
  finetune_percep_weight: 1

  dataset: celeba
  epochs: 50
  train_epoch_clip: 20
  val_epoch_clip: 10
  batch_size: 12
  train_image_size: 160
  lr: 1.0e-5
  lr_decay_factor: 0.5
  lr_decay_epochs: [300, 400]
  lr_warmup_steps: 1
  clip_grad_value: 10
  param_running_avg: 10

  visualize_batch_size: 12
  test_interval: 10
  val_images_interval: 1
  checkpoint_backup_interval: 5
  test_batch_size: 24
