model:
  type: rrdbnet
  input_channels: 3
  sr_factor: 8

  rrdb_num_blocks: 8
  rrdb_block_selection: [7]
  rrdb_network_features: 64
  rrdb_intermediate_features: 32
  rrdb_channels: 64  # rrdb_network_features * len(rrdb_block_selection)

  prior: gaussian

train:
  use_cuda: true
  tensorboard: true
  random_seed: null
  distributed: false

  finetune_pretrained_model: null
  finetune_percep: false
  finetune_pixel: false
  finetune_gan: false

  dataset: celeba
  epochs: 50
  train_epoch_clip: 1000
  batch_size: 64
  train_image_size: 160
  lr: 2.0e-4
  lr_decay_factor: 0.5
  lr_decay_epochs: [30, 40, 45]
  lr_warmup_steps: 500
  clip_grad_value: 10

  visualize_batch_size: 16
  test_interval: 10
  val_images_interval: 1
  checkpoint_backup_interval: 100
